### ISSUE TITLE
dnf repository

### ISSUE THREAD

**Issue by sabrehagen** [gromnitsky/gtk4_shadertoy#1]
When executing `sudo dnf install gtk4-devel` on Ubuntu 23.04 as instructed in the readme, I get the following error:

```sh
> sudo dnf install gtk4-devel
Unable to detect release version (use '--releasever' to specify release version)
Error: There are no enabled repositories in "/etc/yum.repos.d", "/etc/yum/repos.d", "/etc/distro.repos.d".
```

What repository do you have configured that provides gtk4-devel?

**Comment by gromnitsky** [comment]
those instructions are meant for Fedora. I don't use Ubuntu, but I think

    $ sudo apt install libgtk-4-dev

should yield the same result

**Comment by sabrehagen** [comment]
Unfortunately I realised it is for Fedora, yes. Installing `libgtk-4-dev` on Ubuntu does not resolve the issue for me.

**Comment by gromnitsky** [comment]
I installed Ubuntu in a VM, and you're right, the compilation fails on a linkage step

I manage to build it changing 1 line in the Makefile:

~~~
$ git diff
diff --git a/Makefile b/Makefile
index 9880dcd..539c016 100644
--- a/Makefile
+++ b/Makefile
@@ -7,7 +7,7 @@ LDFLAGS := $(shell pkg-config $(libs) --libs)
 deps := $(patsubst %.c, $(out)/%.o, $(wildcard *.c))
 
 $(out)/gtk4_shadertoy: $(deps)
-       $(LINK.c) $^ -o $@
+       $(CC) $^ $(LDFLAGS) -o $@
 
 $(out)/%.o: %.c
        @mkdir -p $(dir $@)
~~~

**Comment by sabrehagen** [comment]
Thank you, that change worked.

Does this change also build on fedora? If so, it would benefit other users to have it merged.

**Comment by sabrehagen** [comment]
Ah I see you already made the change. Closing issue. Thanks for the support.
